#!/bin/bash
#############################################################
## NAMD Equilibration Run Script
## Generated by Gatewizard
#############################################################

# Set NAMD executable
NAMD="namd3"

# Check if NAMD is available
if ! command -v $NAMD &> /dev/null; then
    echo "Error: NAMD executable not found: $NAMD"
    exit 1
fi

echo "Starting NAMD equilibration protocol..."
echo "Each stage uses individual CPU/GPU settings"
echo ""

# Stage 1: Equilibration 1
echo "Running Stage 1: Equilibration 1"
echo "Steps: 125000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step1_equilibration.conf > step1_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 1: Equilibration 1"
    exit 1
fi
echo "Stage 1 completed successfully"
echo ""

# Stage 2: Equilibration 2
echo "Running Stage 2: Equilibration 2"
echo "Steps: 125000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step2_equilibration.conf > step2_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 2: Equilibration 2"
    exit 1
fi
echo "Stage 2 completed successfully"
echo ""

# Stage 3: Equilibration 3
echo "Running Stage 3: Equilibration 3"
echo "Steps: 125000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step3_equilibration.conf > step3_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 3: Equilibration 3"
    exit 1
fi
echo "Stage 3 completed successfully"
echo ""

# Stage 4: Equilibration 4
echo "Running Stage 4: Equilibration 4"
echo "Steps: 250000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step4_equilibration.conf > step4_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 4: Equilibration 4"
    exit 1
fi
echo "Stage 4 completed successfully"
echo ""

# Stage 5: Equilibration 5
echo "Running Stage 5: Equilibration 5"
echo "Steps: 250000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step5_equilibration.conf > step5_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 5: Equilibration 5"
    exit 1
fi
echo "Stage 5 completed successfully"
echo ""

# Stage 6: Equilibration 6
echo "Running Stage 6: Equilibration 6"
echo "Steps: 250000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step6_equilibration.conf > step6_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 6: Equilibration 6"
    exit 1
fi
echo "Stage 6 completed successfully"
echo ""

# Stage 7: Production
echo "Running Stage 7: Production"
echo "Steps: 5000000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step7_production.conf > step7_production.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 7: Production"
    exit 1
fi
echo "Stage 7 completed successfully"
echo ""

echo "All equilibration stages completed successfully!"
echo "Check the log files for detailed output"