"""
Generated by CHARMM-GUI (http://www.charmm-gui.org)

omm_restratins.py

This module contains restraint functions for OpenMM.

Correspondance: jul316@lehigh.edu or wonpil@lehigh.edu
Last update: February 5, 2025
"""

from openmm import *
from openmm.app import *
from openmm.unit import *
import os


def _missing_restraint_file(path):
    print(
        f"WARNING: {path} not found; skipping this restraint "
        "(typical for systems without that component)."
    )


def restraints(system, crd, inputs):

    boxlx = system.getDefaultPeriodicBoxVectors()[0][0].value_in_unit(nanometers)
    boxly = system.getDefaultPeriodicBoxVectors()[1][1].value_in_unit(nanometers)
    boxlz = system.getDefaultPeriodicBoxVectors()[2][2].value_in_unit(nanometers)

    if inputs.fc_bb > 0 or inputs.fc_sc > 0:
        if not os.path.isfile("restraints/prot_pos.txt"):
            _missing_restraint_file("restraints/prot_pos.txt")
        else:
            # positional restraints for protein
            posresPROT = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2;")
            posresPROT.addPerParticleParameter("k")
            posresPROT.addPerParticleParameter("x0")
            posresPROT.addPerParticleParameter("y0")
            posresPROT.addPerParticleParameter("z0")
            for line in open("restraints/prot_pos.txt", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                state = segments[1]
                xpos = crd.positions[atom1].value_in_unit(nanometers)[0]
                ypos = crd.positions[atom1].value_in_unit(nanometers)[1]
                zpos = crd.positions[atom1].value_in_unit(nanometers)[2]
                if state == "BB" and inputs.fc_bb > 0:
                    fc_ppos = inputs.fc_bb
                    posresPROT.addParticle(atom1, [fc_ppos, xpos, ypos, zpos])
                if state == "SC" and inputs.fc_sc > 0:
                    fc_ppos = inputs.fc_sc
                    posresPROT.addParticle(atom1, [fc_ppos, xpos, ypos, zpos])
            system.addForce(posresPROT)

    if inputs.fc_mpos > 0:
        if not os.path.isfile("restraints/lipid_pos.txt"):
            _missing_restraint_file("restraints/lipid_pos.txt")
        else:
            # positional restraints for micelle lipid head group
            posresMICE = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2;")
            posresMICE.addGlobalParameter("k", inputs.fc_mpos)
            posresMICE.addPerParticleParameter("x0")
            posresMICE.addPerParticleParameter("y0")
            posresMICE.addPerParticleParameter("z0")
            for line in open("restraints/lipid_pos.txt", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                xpos = crd.positions[atom1].value_in_unit(nanometers)[0]
                ypos = crd.positions[atom1].value_in_unit(nanometers)[1]
                zpos = crd.positions[atom1].value_in_unit(nanometers)[2]
                posresMICE.addParticle(atom1, [xpos, ypos, zpos])
            system.addForce(posresMICE)

    if inputs.fc_lpos > 0:
        if not os.path.isfile("restraints/lipid_pos.txt"):
            _missing_restraint_file("restraints/lipid_pos.txt")
        else:
            # positional restraints for bilayer lipid head group
            posresMEMB = CustomExternalForce("k*periodicdistance(0, 0, z, 0, 0, z0)^2;")
            posresMEMB.addGlobalParameter("k", inputs.fc_lpos)
            posresMEMB.addPerParticleParameter("z0")
            for line in open("restraints/lipid_pos.txt", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                zpos = crd.positions[atom1].value_in_unit(nanometers)[2]
                posresMEMB.addParticle(atom1, [zpos])
            system.addForce(posresMEMB)

    if inputs.fc_hmmm > 0:
        if not os.path.isfile("restraints/hmmm_pos.txt"):
            _missing_restraint_file("restraints/hmmm_pos.txt")
        else:
            posresHMMM = CustomCentroidBondForce(1, "k*(z1 - z0)^2")
            posresHMMM.addGlobalParameter("k", inputs.fc_hmmm)
            posresHMMM.addPerBondParameter("z0")

            # add groups and bonds
            for i, line in enumerate(open("restraints/hmmm_pos.txt", "r")):
                segments = line.strip().split()
                atoms = list(map(int, segments[:-1]))
                zpos = float(segments[-1]) + boxlz / 2.0
                posresHMMM.addGroup(atoms)
                posresHMMM.addBond([i], [zpos])
            posresHMMM.setUsesPeriodicBoundaryConditions(True)
            system.addForce(posresHMMM)

    if inputs.fc_dcle > 0:
        if not os.path.isfile("restraints/dcle_pos.txt"):
            _missing_restraint_file("restraints/dcle_pos.txt")
        else:
            posresDCLE = CustomCentroidBondForce(1, "k*dr^2; \
                                                    dr=max(0, r-rfb); \
                                                    r=abs(z1 - z0);")
            posresDCLE.addGlobalParameter("k", inputs.fc_dcle)
            posresDCLE.addGlobalParameter("rfb", inputs.fbres_rfb)
            posresDCLE.addGlobalParameter("z0", boxlz / 2.0)

            # add groups and bonds
            for i, line in enumerate(open("restraints/dcle_pos.txt", "r")):
                atoms = list(map(int, line.strip().split()))
                posresDCLE.addGroup(atoms)
                posresDCLE.addBond([i])
            posresDCLE.setUsesPeriodicBoundaryConditions(True)
            system.addForce(posresDCLE)

    if inputs.fc_ldih > 0:
        if not os.path.isfile("restraints/dihe.txt"):
            _missing_restraint_file("restraints/dihe.txt")
        else:
            # dihedral restraints for lipids
            dihresMEMB = CustomTorsionForce("fc_ldih*max(0, abs(diff+wrap) - rwidth)^2; \
                                             wrap = 2*pi*(step(-diff-pi)-step(diff-pi)); \
                                             diff = theta - rtheta0; \
                                             rtheta0 = theta0*pi/180; \
                                             rwidth = width*pi/180;")
            dihresMEMB.addGlobalParameter("fc_ldih", inputs.fc_ldih)
            dihresMEMB.addGlobalParameter("pi", 3.141592653589793)
            dihresMEMB.addPerTorsionParameter("width")
            dihresMEMB.addPerTorsionParameter("theta0")
            for line in open("restraints/dihe.txt", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                atom2 = int(segments[1])
                atom3 = int(segments[2])
                atom4 = int(segments[3])
                theta0 = float(segments[4])
                width = float(segments[5])
                dihresMEMB.addTorsion(atom1, atom2, atom3, atom4, [width, theta0])
            system.addForce(dihresMEMB)

    if inputs.fc_cdih > 0:
        # dihedral restraints for carbohydrates
        dihresCARB = CustomTorsionForce("fc_cdih*max(0, abs(diff+wrap) - rwidth)^2; \
                                         wrap = 2*pi*(step(-diff-pi)-step(diff-pi)); \
                                         diff = theta - rtheta0; \
                                         rtheta0 = theta0*pi/180; \
                                         rwidth = width*pi/180;")
        dihresCARB.addGlobalParameter("fc_cdih", inputs.fc_cdih)
        dihresCARB.addGlobalParameter("pi", 3.141592653589793)
        dihresCARB.addPerTorsionParameter("width")
        dihresCARB.addPerTorsionParameter("theta0")
        if os.path.isfile("restraints/carbohydrate_restraint.dat"):
            for line in open("restraints/carbohydrate_restraint.dat", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                atom2 = int(segments[1])
                atom3 = int(segments[2])
                atom4 = int(segments[3])
                theta0 = float(segments[4])
                width = float(segments[5])
                dihresCARB.addTorsion(atom1, atom2, atom3, atom4, [width, theta0])
        if os.path.isfile("restraints/detergent_carbohydrate_restraint.dat"):
            for line in open("restraints/detergent_carbohydrate_restraint.dat", "r"):
                segments = line.strip().split()
                atom1 = int(segments[0])
                atom2 = int(segments[1])
                atom3 = int(segments[2])
                atom4 = int(segments[3])
                theta0 = float(segments[4])
                width = float(segments[5])
                dihresCARB.addTorsion(atom1, atom2, atom3, atom4, [width, theta0])
        system.addForce(dihresCARB)

    # GateWizard extension: per-atom custom positional restraints
    # (ligands, cofactors, or any molecule not covered by the standard categories)
    # File format: atom_index(0-based)  force_kJ_mol_nm2
    # The .inp parameter 'custom_pos_file' points to a per-stage file so each
    # stage can have its own force constants; falls back to the shared file.
    _custom_pos_path = (
        getattr(inputs, "custom_pos_file", "") or "restraints/custom_pos.txt"
    )
    if os.path.exists(_custom_pos_path):
        posresCUSTOM = CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
        posresCUSTOM.addPerParticleParameter("k")
        posresCUSTOM.addPerParticleParameter("x0")
        posresCUSTOM.addPerParticleParameter("y0")
        posresCUSTOM.addPerParticleParameter("z0")
        for line in open(_custom_pos_path, "r"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            seg = line.split()
            atom1 = int(seg[0])
            k = float(seg[1])
            xpos = crd.positions[atom1].value_in_unit(nanometers)[0]
            ypos = crd.positions[atom1].value_in_unit(nanometers)[1]
            zpos = crd.positions[atom1].value_in_unit(nanometers)[2]
            posresCUSTOM.addParticle(atom1, [k, xpos, ypos, zpos])
        system.addForce(posresCUSTOM)

    # GateWizard extension: COM (centre-of-mass / centre-of-geometry) restraint
    # Restrains the centroid of selected atoms (Cα by default) to its initial
    # position via CustomCentroidBondForce — no per-atom positional bias.
    # Force constant: kcal/mol/Å² (converted to kJ/mol/nm² below).
    # JSON keys: ca_indices, centroid_angstrom, force_constant_kcal_mol_A2
    if os.path.exists("com_restraint_params.json"):
        import json as _json

        _KCAL_TO_KJ_NM2 = 418.4  # 1 kcal/mol/Å² = 418.4 kJ/mol/nm²
        with open("com_restraint_params.json") as _f:
            _com = _json.load(_f)
        _indices = _com["ca_indices"]
        _c = _com["centroid_angstrom"]  # Å
        # centroid in nm (OpenMM native unit)
        _x0_nm, _y0_nm, _z0_nm = _c[0] / 10.0, _c[1] / 10.0, _c[2] / 10.0
        _fc_kj = _com["force_constant_kcal_mol_A2"] * _KCAL_TO_KJ_NM2
        # Use CustomCentroidBondForce(1 group, energy expression).
        # group1 centroid is (x1,y1,z1); the target is a global parameter.
        _comForce = CustomCentroidBondForce(
            1,
            "0.5*k_com*((x1-x0_com)^2 + (y1-y0_com)^2 + (z1-z0_com)^2)",
        )
        _comForce.addGlobalParameter("k_com", _fc_kj)
        _comForce.addGlobalParameter("x0_com", _x0_nm)
        _comForce.addGlobalParameter("y0_com", _y0_nm)
        _comForce.addGlobalParameter("z0_com", _z0_nm)
        _comForce.addGroup(_indices)
        _comForce.addBond([0])
        _comForce.setUsesPeriodicBoundaryConditions(True)
        system.addForce(_comForce)

        # Optional rotational restraint: use three C-alpha anchor atoms and
        # restrain two reference vectors to keep the rigid-body orientation.
        if _com.get("add_rotation_restraint", False):
            _anchor = _com.get("rotation_anchor_indices", [])
            _ref = _com.get("rotation_ref_positions_angstrom", [])
            _rot_k_kcal = _com.get("rotation_force_constant_kcal_mol_A2", 2000.0)

            if len(_anchor) == 3 and len(_ref) == 3:
                _r1 = [_ref[0][0] / 10.0, _ref[0][1] / 10.0, _ref[0][2] / 10.0]
                _r2 = [_ref[1][0] / 10.0, _ref[1][1] / 10.0, _ref[1][2] / 10.0]
                _r3 = [_ref[2][0] / 10.0, _ref[2][1] / 10.0, _ref[2][2] / 10.0]

                _dx12 = _r1[0] - _r2[0]
                _dy12 = _r1[1] - _r2[1]
                _dz12 = _r1[2] - _r2[2]
                _dx13 = _r1[0] - _r3[0]
                _dy13 = _r1[1] - _r3[1]
                _dz13 = _r1[2] - _r3[2]

                _rotForce = CustomCompoundBondForce(
                    3,
                    "0.5*krot*((x1-x2-dx12)^2 + (y1-y2-dy12)^2 + (z1-z2-dz12)^2 + "
                    "(x1-x3-dx13)^2 + (y1-y3-dy13)^2 + (z1-z3-dz13)^2)",
                )
                _rotForce.addGlobalParameter("krot", _rot_k_kcal * _KCAL_TO_KJ_NM2)
                _rotForce.addPerBondParameter("dx12")
                _rotForce.addPerBondParameter("dy12")
                _rotForce.addPerBondParameter("dz12")
                _rotForce.addPerBondParameter("dx13")
                _rotForce.addPerBondParameter("dy13")
                _rotForce.addPerBondParameter("dz13")
                _rotForce.addBond(
                    [int(_anchor[0]), int(_anchor[1]), int(_anchor[2])],
                    [_dx12, _dy12, _dz12, _dx13, _dy13, _dz13],
                )
                _rotForce.setUsesPeriodicBoundaryConditions(True)
                system.addForce(_rotForce)
            else:
                print(
                    "WARNING: OpenMM rotation restraint requested but anchor atoms "
                    "are missing in com_restraint_params.json"
                )

    return system
