#!/bin/bash
# Cluster runner - use after module load; called by run_equilibration.slurm
## OpenMM Equilibration Run Script
## Generated by GateWizard - run from the directory containing this file

# --- Platform selection ---
# Default PLATFORM used for GPU stages when empty -> openmm_run auto-picks
# CUDA > OpenCL > CPU. CPU stages force --platform CPU.
# Override with: PLATFORM=CPU bash run_equilibration.sh
# Override with: PLATFORM=OpenCL bash run_equilibration.sh
PLATFORM="${PLATFORM:-}"

# GPU device index (OpenMM DeviceIndex / OpenCLDeviceIndex)
DEVICE_INDEX="${DEVICE_INDEX:-0}"

# Default CPU thread count (per-stage may override)
THREADS="${THREADS:-1}"

# Override Python interpreter with: PYTHON=python3 bash run_equilibration_cluster.sh
PYTHON="${PYTHON:-python}"
PRMTOP="system.prmtop"
INPCRD="system.inpcrd"

echo "Starting OpenMM equilibration protocol..."
echo "Resources: 1 CPU threads (default), GPU device(s) 0, 1 CPU + 1 GPU for ALL stages (incl. first packing barostat)"

# Stage-level resume: skip stages that already finished (not mid-stage checkpoints).
# RESUME=1 bash run_equilibration.sh
RESUME="${RESUME:-0}"

_gw_openmm_stage_done() {
  local stem="$1"
  [ -f "${stem}.rst" ] && grep -qE '100(\.0)?%' "${stem}.log" 2>/dev/null
}

# Stage 1: step1_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step1_equilibration"; then
  echo "RESUME: skipping stage 1 (step1_equilibration)"
else
  echo "Stage 1 (step1_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step1_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -orst step1_equilibration.rst -odcd step1_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step1_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 1 (step1_equilibration) failed"; exit 1; fi
fi

# Stage 2: step2_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step2_equilibration"; then
  echo "RESUME: skipping stage 2 (step2_equilibration)"
else
  echo "Stage 2 (step2_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step2_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -irst step1_equilibration.rst -orst step2_equilibration.rst -odcd step2_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step2_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 2 (step2_equilibration) failed"; exit 1; fi
fi

# Stage 3: step3_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step3_equilibration"; then
  echo "RESUME: skipping stage 3 (step3_equilibration)"
else
  echo "Stage 3 (step3_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step3_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -irst step2_equilibration.rst -orst step3_equilibration.rst -odcd step3_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step3_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 3 (step3_equilibration) failed"; exit 1; fi
fi

# Stage 4: step4_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step4_equilibration"; then
  echo "RESUME: skipping stage 4 (step4_equilibration)"
else
  echo "Stage 4 (step4_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step4_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -irst step3_equilibration.rst -orst step4_equilibration.rst -odcd step4_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step4_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 4 (step4_equilibration) failed"; exit 1; fi
fi

# Stage 5: step5_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step5_equilibration"; then
  echo "RESUME: skipping stage 5 (step5_equilibration)"
else
  echo "Stage 5 (step5_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step5_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -irst step4_equilibration.rst -orst step5_equilibration.rst -odcd step5_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step5_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 5 (step5_equilibration) failed"; exit 1; fi
fi

# Stage 6: step6_equilibration
if [ "$RESUME" = "1" ] && _gw_openmm_stage_done "step6_equilibration"; then
  echo "RESUME: skipping stage 6 (step6_equilibration)"
else
  echo "Stage 6 (step6_equilibration): GPU platform (auto)"
  ($PYTHON openmm_run.py -i step6_equilibration.inp -ff amber -p $PRMTOP -c $INPCRD -irst step5_equilibration.rst -orst step6_equilibration.rst -odcd step6_equilibration.dcd ${PLATFORM:+--platform $PLATFORM} ${DEVICE_INDEX:+--device $DEVICE_INDEX} --threads 1) 2>&1 | tee step6_equilibration.log
  if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "Stage 6 (step6_equilibration) failed"; exit 1; fi
fi

echo "Equilibration complete."
