#!/usr/bin/env python3
"""
MemPrO Test Suite

This test suite covers:
1. Core MemPrO API (MemPrO class, OrientationResult, parse_results)
2. Documentation example workflows (Examples 1-12)

The test suite automatically discovers and runs all example scripts from:
    tests/mempro_examples/mempro_example_*.py

Note: Some tests require the mempro executable and real PDB files.
Tests that need mempro are skipped if it is not installed.

Usage:
    # Run all tests
    pytest tests/test_mempro.py -v

    # Run only example tests
    pytest tests/test_mempro.py::TestMemProExamples -v

    # Run specific example
    pytest tests/test_mempro.py::TestMemProExamples::test_individual_examples[01] -v

    # Run examples manually (outside pytest)
    python tests/test_mempro.py
"""

import pytest
import sys
import os
import shutil
import tempfile
from pathlib import Path
import importlib.util

sys.path.insert(0, str(Path(__file__).parent.parent))

from gatewizard.core.mempro import MemPrO, OrientationResult, MemProError

# Sample orientation.txt content for testing
SAMPLE_ORIENTATION_TXT = """\
Generated by command: /usr/bin/mempro -f test.pdb
Rank \t Relative potential \t % hits \t Re-rank pots \t Re-rank minima depth \t Re-rank values
1\t -24.125\t47.222\t-24.128\t132.073\t62763.403
2\t -3.72\t2.778\t-3.560\t3.560\t24511.650
3\t -3.078\t11.111\t-3.548\t3.548\t24506.777
"""

MINI_PDB = """\
HEADER    TEST PROTEIN
ATOM      1  N   ALA A   1       1.000   2.000   3.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       2.000   2.000   3.000  1.00  0.00           C
ATOM      3  C   ALA A   1       3.000   2.000   3.000  1.00  0.00           C
ATOM      4  O   ALA A   1       3.500   3.000   3.000  1.00  0.00           O
END
"""


@pytest.fixture
def orient_dir(tmp_path):
    """Create a mock Orient directory with orientation.txt and ranked PDBs."""
    orient = tmp_path / "Orient"
    orient.mkdir()
    (orient / "orientation.txt").write_text(SAMPLE_ORIENTATION_TXT)
    for rank in range(1, 4):
        rank_dir = orient / f"Rank_{rank}"
        rank_dir.mkdir()
        (rank_dir / f"oriented_rank_{rank}.pdb").write_text(MINI_PDB)
    return str(orient)


@pytest.fixture
def temp_dir(tmp_path):
    """Provide a temporary directory for test outputs."""
    orig = os.getcwd()
    os.chdir(tmp_path)
    yield tmp_path
    os.chdir(orig)


# ============================================================================
# SECTION 1: CORE API TESTS
# ============================================================================


class TestMemPrO:
    """Test the MemPrO class core functionality."""

    def test_instantiation(self):
        """Test that MemPrO can be instantiated."""
        mp = MemPrO()
        assert mp is not None

    def test_is_available_returns_bool(self):
        """Test that is_available returns a boolean."""
        result = MemPrO.is_available()
        assert isinstance(result, bool)

    def test_parse_results(self, orient_dir):
        """Test parsing orientation results from a directory."""
        results = MemPrO.parse_results(orient_dir)
        assert len(results) == 3
        assert results[0].rank == 1
        assert results[1].rank == 2
        assert results[2].rank == 3

    def test_parse_results_values(self, orient_dir):
        """Test that parsed values match the sample data."""
        results = MemPrO.parse_results(orient_dir)
        r1 = results[0]
        assert r1.relative_potential == pytest.approx(-24.125)
        assert r1.hits_pct == pytest.approx(47.222)
        assert r1.rerank_potential == pytest.approx(-24.128)
        assert r1.rerank_depth == pytest.approx(132.073)
        assert r1.rerank_value == pytest.approx(62763.403)

    def test_parse_results_pdb_paths(self, orient_dir):
        """Test that PDB paths are resolved correctly."""
        results = MemPrO.parse_results(orient_dir)
        for r in results:
            assert r.pdb_path != ""
            assert os.path.isfile(r.pdb_path)

    def test_parse_results_missing_dir(self, tmp_path):
        """Test that missing directory raises MemProError."""
        with pytest.raises(MemProError):
            MemPrO.parse_results(str(tmp_path / "nonexistent"))

    def test_parse_results_missing_txt(self, tmp_path):
        """Test that missing orientation.txt raises MemProError."""
        d = tmp_path / "Orient"
        d.mkdir()
        with pytest.raises(MemProError):
            MemPrO.parse_results(str(d))

    def test_get_oriented_pdb(self, orient_dir):
        """Test getting an oriented PDB by rank."""
        pdb = MemPrO.get_oriented_pdb(orient_dir, rank=1)
        assert os.path.isfile(pdb)
        assert "oriented_rank_1.pdb" in pdb

    def test_get_oriented_pdb_rank2(self, orient_dir):
        """Test getting rank 2 PDB."""
        pdb = MemPrO.get_oriented_pdb(orient_dir, rank=2)
        assert "oriented_rank_2.pdb" in pdb

    def test_get_oriented_pdb_missing(self, orient_dir):
        """Test that missing rank raises FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            MemPrO.get_oriented_pdb(orient_dir, rank=99)

    def test_run_missing_pdb(self):
        """Test that run raises FileNotFoundError for missing input."""
        mp = MemPrO()
        with pytest.raises(FileNotFoundError):
            mp.run("/nonexistent/path/protein.pdb")

    @pytest.mark.skipif(not MemPrO.is_available(), reason="mempro not installed")
    def test_build_command(self):
        """Test building a command line."""
        mp = MemPrO()
        cmd = mp.build_command("test.pdb", n_cpus=4, dual_membrane=True)
        assert "-f" in cmd
        assert "-nc" in cmd
        assert "4" in cmd
        assert "-dm" in cmd

    @pytest.mark.skipif(not MemPrO.is_available(), reason="mempro not installed")
    def test_build_command_defaults(self):
        """Test that default command only has -f."""
        mp = MemPrO()
        cmd = mp.build_command("test.pdb")
        assert cmd[-1].endswith("test.pdb") or "test.pdb" in cmd[-1]
        # Should NOT have optional flags
        assert "-dm" not in cmd
        assert "-pr" not in cmd
        assert "-nc" not in cmd

    def test_orientation_result_repr(self):
        """Test OrientationResult string representation."""
        r = OrientationResult(
            rank=1,
            relative_potential=-24.125,
            hits_pct=47.222,
            rerank_potential=-24.128,
            rerank_depth=132.073,
            rerank_value=62763.403,
            pdb_path="/tmp/oriented_rank_1.pdb",
        )
        s = repr(r)
        assert "rank=1" in s
        assert "-24.125" in s

    def test_sorted_by_rank(self, orient_dir):
        """Test that results are sorted by rank."""
        results = MemPrO.parse_results(orient_dir)
        ranks = [r.rank for r in results]
        assert ranks == sorted(ranks)


# ============================================================================
# SECTION 2: EXAMPLE TESTS
# ============================================================================


class TestMemProExamples:
    """Test mempro examples from mempro_examples directory."""

    @pytest.fixture
    def temp_dir(self, tmp_path):
        """Provide a temporary directory for test outputs."""
        orig = os.getcwd()
        os.chdir(tmp_path)
        yield tmp_path
        os.chdir(orig)

    @pytest.fixture(autouse=True)
    def cleanup_orient_dirs(self):
        """Clean up Orient and my_orient directories created by mempro examples."""
        yield
        for dir_name in ("Orient", "my_orient"):
            target = Path(dir_name)
            if target.exists():
                for attempt in range(3):
                    try:
                        shutil.rmtree(target)
                        break
                    except (PermissionError, OSError):
                        import time as _time

                        _time.sleep(1)

    def test_run_example_scripts(self, temp_dir):
        """Test running actual example scripts from mempro_examples directory."""
        examples_dir = Path(__file__).parent / "mempro_examples"

        if not examples_dir.exists():
            pytest.skip(f"Examples directory not found: {examples_dir}")

        example_files = sorted(examples_dir.glob("mempro_example_*.py"))

        if not example_files:
            pytest.skip("No example files found in mempro_examples directory")

        print(f"\nFound {len(example_files)} example files to test")

        failed_examples = []
        passed_examples = []

        for example_file in example_files:
            example_num = example_file.stem.split("_")[-1]

            spec = importlib.util.spec_from_file_location(
                f"mempro_example_{example_num}", example_file
            )

            if spec is None or spec.loader is None:
                failed_examples.append((example_num, "Could not load module"))
                continue

            module = importlib.util.module_from_spec(spec)

            try:
                print(f"\nTesting Example {example_num}: {example_file.name}")
                spec.loader.exec_module(module)
                print(f"  Example {example_num} executed successfully")
                passed_examples.append(example_num)
            except Exception as e:
                error_msg = f"{type(e).__name__}: {str(e)}"
                print(f"  Example {example_num} failed: {error_msg}")
                failed_examples.append((example_num, error_msg))

        print(
            f"\nSummary: {len(passed_examples)} passed, "
            f"{len(failed_examples)} failed"
        )

        if failed_examples:
            for num, error in failed_examples:
                print(f"  Failed {num}: {error}")
            pytest.fail(f"{len(failed_examples)} example(s) failed")

    @pytest.mark.parametrize("example_num", [f"{i:02d}" for i in range(1, 13)])
    def test_individual_examples(self, example_num, temp_dir):
        """Test each example individually for better pytest reporting."""
        examples_dir = Path(__file__).parent / "mempro_examples"
        example_file = examples_dir / f"mempro_example_{example_num}.py"

        if not example_file.exists():
            pytest.skip(f"Example {example_num} not found")

        spec = importlib.util.spec_from_file_location(
            f"mempro_example_{example_num}", example_file
        )

        if spec is None or spec.loader is None:
            pytest.fail(f"Could not load example {example_num}")

        module = importlib.util.module_from_spec(spec)

        try:
            spec.loader.exec_module(module)
        except Exception as e:
            pytest.fail(f"Example {example_num} failed: {type(e).__name__}: {str(e)}")


# ============================================================================
# MAIN (for running outside pytest)
# ============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("MemPrO Test Suite - Manual Run")
    print("=" * 60)

    examples_dir = Path(__file__).parent / "mempro_examples"

    if not examples_dir.exists():
        print(f"Examples directory not found: {examples_dir}")
        sys.exit(1)

    example_files = sorted(examples_dir.glob("mempro_example_*.py"))

    if not example_files:
        print("No example files found")
        sys.exit(1)

    print(f"Found {len(example_files)} examples to run\n")

    passed = 0
    failed = 0

    for example_file in example_files:
        example_num = example_file.stem.split("_")[-1]
        print(f"Running Example {example_num}: {example_file.name}")

        spec = importlib.util.spec_from_file_location(
            f"mempro_example_{example_num}", example_file
        )
        if spec is None or spec.loader is None:
            print(f"  SKIP: Could not load")
            continue

        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)
            print(f"  PASSED")
            passed += 1
        except Exception as e:
            print(f"  FAILED: {type(e).__name__}: {e}")
            failed += 1

    print(f"\n{'=' * 60}")
    print(f"Results: {passed} passed, {failed} failed " f"out of {len(example_files)}")
