"""Tests for equilibration template header stamping."""

from datetime import datetime, timezone, timedelta

from gatewizard.utils.equilibration_templates import (
    EQUILIBRATION_TEMPLATES_VERSION,
    format_generated_on,
    normalize_scheme_label,
    stamp_equilibration_header,
)


def test_format_generated_on_includes_timezone():
    dt = datetime(2026, 7, 27, 14, 12, tzinfo=timezone(timedelta(hours=-4)))
    text = format_generated_on(dt)
    assert "27 Jul 2026 at 14:12" in text
    assert "UTC-4" in text


def test_stamp_namd_header_replaces_placeholders():
    raw = (
        "# Generated by GateWizard v{GW_VERSION} on {GW_GENERATED_ON}\n"
        "# Templates version: testing (27 Jul 2026)\n"
        "# Adapted from CHARMM-GUI\n"
        "# NVT SCHEME for NAMD - template step7_production.inp\n"
        "\n"
        "langevin on\n"
    )
    out = stamp_equilibration_header(
        raw,
        engine="namd",
        scheme="NVT",
        template_filename="step7_production.inp",
        api_version="1.0.52",
        generated_on="27 Jul 2026 at 14:12 EDT",
    )
    assert out.startswith("# Generated by GateWizard v1.0.52 on 27 Jul 2026 at 14:12 EDT\n")
    assert f"Templates version: {EQUILIBRATION_TEMPLATES_VERSION}" in out
    assert "{GW_VERSION}" not in out
    assert "langevin on" in out


def test_stamp_amber_header_after_cntrl():
    raw = (
        "A NVT simulation for common production-level simulations\n"
        " &cntrl\n"
        "    ! Generated by GateWizard v{GW_VERSION} on {GW_GENERATED_ON}\n"
        "    imin=0,\n"
        " /\n"
    )
    out = stamp_equilibration_header(
        raw,
        engine="amber",
        scheme="NVT",
        template_filename="step3_equilibration.mdin",
        api_version="1.0.52",
        generated_on="27 Jul 2026 at 14:12 EDT",
    )
    assert out.splitlines()[0].startswith("A NVT")
    assert " &cntrl" in out
    assert "! Generated by GateWizard v1.0.52 on 27 Jul 2026 at 14:12 EDT" in out
    assert "NVT SCHEME for Amber - template step3_equilibration.mdin" in out
    assert "imin=0," in out


def test_npgt_header_keeps_lowercase_g():
    assert normalize_scheme_label("NPgT") == "NPgT"
    assert normalize_scheme_label("npgt") == "NPgT"
    assert normalize_scheme_label("NPGT") == "NPgT"
    out = stamp_equilibration_header(
        "# old\n\nrun\n",
        engine="namd",
        scheme="NPgT",
        template_filename="step7_production.inp",
        api_version="1.0.52",
        generated_on="27 Jul 2026 at 14:12 EDT",
    )
    assert "NPgT SCHEME for NAMD" in out
    assert "NPGT SCHEME" not in out
