#!/bin/bash
#############################################################
## NAMD Equilibration Run Script
## Generated by Gatewizard
#############################################################

# Set NAMD executable
NAMD="namd3"

# Check if NAMD is available
if ! command -v $NAMD &> /dev/null; then
    echo "Error: NAMD executable not found: $NAMD"
    exit 1
fi

echo "Starting NAMD equilibration protocol..."
echo "Each stage uses individual CPU/GPU settings"
echo ""

# Stage 1: Initial Equilibration
echo "Running Stage 1: Initial Equilibration"
echo "Steps: 250000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step1_equilibration.conf > step1_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 1: Initial Equilibration"
    exit 1
fi
echo "Stage 1 completed successfully"
echo ""

# Stage 2: Pressure Equilibration
echo "Running Stage 2: Pressure Equilibration"
echo "Steps: 500000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step2_equilibration.conf > step2_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 2: Pressure Equilibration"
    exit 1
fi
echo "Stage 2 completed successfully"
echo ""

# Stage 3: Membrane Relaxation
echo "Running Stage 3: Membrane Relaxation"
echo "Steps: 500000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step3_equilibration.conf > step3_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 3: Membrane Relaxation"
    exit 1
fi
echo "Stage 3 completed successfully"
echo ""

# Stage 4: Production Preparation
echo "Running Stage 4: Production Preparation"
echo "Steps: 1000000, Timestep: 2.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step4_equilibration.conf > step4_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 4: Production Preparation"
    exit 1
fi
echo "Stage 4 completed successfully"
echo ""

echo "All equilibration stages completed successfully!"
echo "Check the log files for detailed output"