#!/bin/bash
#############################################################
## NAMD Equilibration Run Script
## Generated by Gatewizard
#############################################################

# Set NAMD executable
NAMD="namd3"

# Check if NAMD is available
if ! command -v $NAMD &> /dev/null; then
    echo "Error: NAMD executable not found: $NAMD"
    exit 1
fi

echo "Starting NAMD equilibration protocol..."
echo "Each stage uses individual CPU/GPU settings"
echo ""

# Stage 1: Equilibration 1
echo "Running Stage 1: Equilibration 1"
echo "Steps: 125000, Timestep: 1.0 ps"
echo "Resources: 1 CPU cores, GPU: No"
$NAMD +p1 step1_equilibration.conf > step1_equilibration.log 2>&1

if [ $? -ne 0 ]; then
    echo "Error in Stage 1: Equilibration 1"
    exit 1
fi
echo "Stage 1 completed successfully"
echo ""

echo "All equilibration stages completed successfully!"
echo "Check the log files for detailed output"