"""Equilibration template metadata and input-file header stamping."""

from __future__ import annotations

import re
from datetime import datetime
from typing import Optional

from gatewizard import __version__ as GATEWIZARD_VERSION

# Bump when any file under equilibration/{namd,gromacs,openmm,amber}/ changes.
EQUILIBRATION_TEMPLATES_VERSION = "v1"
EQUILIBRATION_TEMPLATES_DATE = "27 Jul 2026"

_ENGINE_LABEL = {
    "namd": "NAMD",
    "gromacs": "Gromacs",
    "openmm": "OpenMM",
    "amber": "Amber",
}


def format_generated_on(when: Optional[datetime] = None) -> str:
    """Human-readable local timestamp with timezone name or UTC offset fallback."""
    dt = when or datetime.now().astimezone()
    zone = (dt.tzname() or "").strip()
    # Prefer named zones (EDT, CET). Fall back to UTC±H for numeric / ISO-style names.
    use_offset = (
        not zone
        or zone.upper() in {"LOCAL", "NONE"}
        or re.fullmatch(r"[+-]?\d{2}(?::?\d{2})?", zone) is not None
        or re.fullmatch(r"UTC[+-]\d{1,2}(?::\d{2})?", zone, re.I) is not None
    )
    if use_offset:
        off = dt.utcoffset()
        if off is not None:
            hours = int(off.total_seconds() // 3600)
            zone = f"UTC{hours:+d}"
        else:
            zone = "local"
    return f"{dt.day} {dt.strftime('%b %Y')} at {dt.strftime('%H:%M')} {zone}"


def _comment_prefix(engine: str) -> str:
    eng = engine.lower()
    if eng == "gromacs":
        return ";"
    if eng == "amber":
        return "!"
    return "#"


def build_header_lines(
    *,
    engine: str,
    scheme: str,
    template_filename: str,
    api_version: Optional[str] = None,
    generated_on: Optional[str] = None,
    amber_indent: str = "",
) -> list[str]:
    """Return header lines (without trailing newlines) for an equilibration input."""
    c = _comment_prefix(engine)
    indent = amber_indent if engine.lower() == "amber" else ""
    ver = api_version or GATEWIZARD_VERSION
    when = generated_on or format_generated_on()
    eng_label = _ENGINE_LABEL.get(engine.lower(), engine)
    return [
        f"{indent}{c} Generated by GateWizard v{ver} on {when}",
        f"{indent}{c} Templates version: {EQUILIBRATION_TEMPLATES_VERSION} ({EQUILIBRATION_TEMPLATES_DATE})",
        f"{indent}{c} Adapted from CHARMM-GUI",
        f"{indent}{c} {scheme} SCHEME for {eng_label} - template {template_filename}",
    ]


def normalize_scheme_label(scheme: str) -> str:
    """Canonical ensemble label for headers (``NPgT`` keeps lowercase g)."""
    key = scheme.strip().upper().replace("Γ", "G")
    if key == "NPGT":
        return "NPgT"
    if key in {"NVT", "NPT", "NPAT"}:
        return key
    return scheme.strip()


def stamp_equilibration_header(
    content: str,
    *,
    engine: str,
    scheme: str,
    template_filename: str,
    api_version: Optional[str] = None,
    generated_on: Optional[str] = None,
) -> str:
    """Insert or refresh the GateWizard provenance header in template/generated text."""
    eng = engine.lower()
    scheme = normalize_scheme_label(scheme)
    header_lines = build_header_lines(
        engine=eng,
        scheme=scheme,
        template_filename=template_filename,
        api_version=api_version,
        generated_on=generated_on,
        amber_indent="    " if eng == "amber" else "",
    )
    header_block = "\n".join(header_lines) + "\n"

    if eng == "amber":
        return _stamp_amber(content, header_block)

    c = _comment_prefix(eng)
    lines = content.splitlines(keepends=True)
    i = 0
    while i < len(lines) and lines[i].lstrip().startswith(c):
        body = lines[i].lstrip()[len(c) :].strip().lower()
        if (
            body.startswith("generated by gatewizard")
            or body.startswith("templates version:")
            or body.startswith("adapted from charmm-gui")
            or "scheme for" in body
        ):
            i += 1
            continue
        break
    # Drop one blank line after old header if present
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    rest = "".join(lines[i:])
    if rest.startswith("\n"):
        return header_block + rest
    return header_block + "\n" + rest


def _stamp_amber(content: str, header_block: str) -> str:
    """Place provenance comments immediately after ``&cntrl``."""
    lines = content.splitlines(keepends=True)
    cntrl_idx = None
    for i, line in enumerate(lines):
        if re.match(r"\s*&cntrl\b", line, re.I):
            cntrl_idx = i
            break
    if cntrl_idx is None:
        return header_block + content

    j = cntrl_idx + 1
    while j < len(lines):
        stripped = lines[j].strip()
        if not stripped.startswith("!"):
            break
        body = stripped.lstrip("!").strip().lower()
        if (
            body.startswith("generated by gatewizard")
            or body.startswith("templates version:")
            or body.startswith("adapted from charmm-gui")
            or "scheme for amber" in body
            or body.startswith("gatewizard:")
        ):
            j += 1
            continue
        break

    return "".join(lines[: cntrl_idx + 1]) + header_block + "".join(lines[j:])
